server:
  port: 8085

mybatis:
  type-aliases-package: com.example.dao.entity
  mapper-locations: classpath:mapper/*.xml
  #  ??????
  configuration:
    cache-enabled: true


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/project02?serverTimezone=Asia/Shanghai&characterEncoding=utf-8
    username: root
    password: xyh5019@
    driver-class-name: com.mysql.cj.jdbc.Driver
